# Generated by Django 3.1.6 on 2021-02-06 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='help_description',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Описание помощи'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='charity.category'),
        ),
    ]
